# ==============================================================================
# Конфигурация RoadRunner для Laravel Octane
# ==============================================================================
# Документация: https://docs.roadrunner.dev
#
# Этот файл используется как для разработки, так и для продакшена.
# Переменные окружения позволяют переопределять значения без изменения файла.
# ==============================================================================

version: "3"

# ------------------------------------------------------------------------------
# HTTP-сервер
# ------------------------------------------------------------------------------
http:
  address: "0.0.0.0:8000"
  middleware:
    - "headers"
    - "gzip"
  headers:
    response:
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "SAMEORIGIN"
      X-XSS-Protection: "1; mode=block"
      Referrer-Policy: "strict-origin-when-cross-origin"
  pool:
    # Количество воркеров (процессов PHP)
    # В разработке достаточно 2, в продакшене — по числу ядер CPU
    num_workers: ${RR_HTTP_NUM_WORKERS:-4}
    # Максимальное количество задач на воркер до перезапуска (защита от утечек памяти)
    max_jobs: ${RR_HTTP_MAX_JOBS:-500}
    # Таймаут на выделение воркера для обработки запроса
    allocate_timeout: 60s
    # Таймаут на уничтожение воркера
    destroy_timeout: 60s
  # Максимальный размер тела запроса (загрузка файлов)
  max_request_size: 20
  # Директория для временных загружаемых файлов
  uploads:
    dir: "/tmp"
  # Статические файлы (public/)
  static:
    dir: "/var/www/laravel/public"
    forbid:
      - ".php"
      - ".env"
      - ".htaccess"

# ------------------------------------------------------------------------------
# Сервер (общие настройки воркеров)
# ------------------------------------------------------------------------------
server:
  command: "php worker.php"
  relay: "pipes"

# ------------------------------------------------------------------------------
# Логирование
# ------------------------------------------------------------------------------
logs:
  mode: "production"
  level: ${RR_LOG_LEVEL:-info}
  encoding: "json"
  output: "stderr"

# ------------------------------------------------------------------------------
# Healthcheck endpoint
# ------------------------------------------------------------------------------
status:
  address: "0.0.0.0:2114"

# ------------------------------------------------------------------------------
# Метрики (Prometheus-совместимые)
# ------------------------------------------------------------------------------
# Раскомментируйте для включения метрик:
# metrics:
#   address: "0.0.0.0:2112"

# ------------------------------------------------------------------------------
# Graceful shutdown
# ------------------------------------------------------------------------------
endure:
  threshold: 1
  log_level: "error"
